SENSEI.NETCORE/SENSEI.WEB/Controllers/LayoutController.cs
using Microsoft.AspNetCore.Mvc;
using SENSEI.BLL.AdminPortalService.Interface;
using SENSEI.DOMAIN;
using SENSEI.WEB.Models;
using System.Text.Json;

namespace SENSEI.WEB.Controllers
{
    public class LayoutController : Controller
    {
        private IUserNotificationService _userNotificationService;

        public LayoutController(IUserNotificationService userNotificationService)
        {
            _userNotificationService = userNotificationService;
        }
        public async Task<IActionResult> AdminSidebar()
        {
            var jsonPath = Path.Combine(Directory.GetCurrentDirectory(), "AdminNavigationidebar.json");
            var json = await System.IO.File.ReadAllTextAsync(jsonPath);

            var sidebarItems = JsonSerializer.Deserialize<List<SidebarItem>>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            return View(sidebarItems);
        }

        public async Task<IActionResult> StudentSidebar()
        {
            var jsonPath = Path.Combine(Directory.GetCurrentDirectory(), "StudentNavigationidebar.json");
            var json = await System.IO.File.ReadAllTextAsync(jsonPath);

            var sidebarItems = JsonSerializer.Deserialize<List<SidebarItem>>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

            return View(sidebarItems);
        }

        public async Task<IActionResult> AdminPortalNotification()
        {
            var userId = Convert.ToInt64(HttpContext.Session.GetString("UserId"));
            var notifications = await _userNotificationService.GetUserNotificationForUser(userId);

            //var notifications = new List<UserNotification>
            //{
            //    new UserNotification
            //    {
            //        UserNotificationId = 1,
            //        NotificationType = "System",
            //        Message = "Your profile was updated successfully.",
            //        IsRead = false,
            //        CreatedAt = DateTime.Now.AddMinutes(-5),
            //        Icon = "user",
            //        IsDeleted = false
            //    },
            //    new UserNotification
            //    {
            //        UserNotificationId = 2,
            //        NotificationType = "Course",
            //        Message = "New lesson has been added to your course.",
            //        IsRead = false,
            //        CreatedAt = DateTime.Now.AddHours(-1),
            //        Icon = "book-open",
            //        IsDeleted = false
            //    },
            //    new UserNotification
            //    {
            //        UserNotificationId = 3,
            //        NotificationType = "Payment",
            //        Message = "Your payment was received successfully.",
            //        IsRead = true,
            //        CreatedAt = DateTime.Now.AddDays(-1),
            //        Icon = "credit-card",
            //        IsDeleted = false
            //    }
            //};


            return View(notifications);
        }

        public async Task<IActionResult> StudentPortalNotification()
        {
            return View();
        }

        public async Task<IActionResult> AdminPortalMessages()
        {
            return View();
        }

        public async Task<IActionResult> StudentPortalMessages()
        {
            return View();
        }

        public async Task<IActionResult> AdminPortalProfile()
        {
            return View();
        }

        public async Task<IActionResult> StudentPortalProfile()
        {
            return View();
        }

        public async Task<IActionResult> AdminPortalHeader()
        {
            return View();
        }

        public async Task<IActionResult> AdminPortalFooter()
        {
            return View();
        }

        public async Task<IActionResult> StudentPortalHeader()
        {
            return View();
        }

        public async Task<IActionResult> StudentPortalFooter()
        {
            return View();
        }
    }
}

SENSEI.NETCORE/SENSEI.WEB/Controllers/SenseiJapaneseSchoolController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.Google;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using Newtonsoft.Json;
using SENSEI.BLL.AdminPortalService.Interface;
using SENSEI.BLL.SystemService.Interfaces;
using SENSEI.DOMAIN;
using SENSEI.WEB.Helpers;
using System.Net.Http.Headers;
using System.Runtime.InteropServices.JavaScript;
using System.Security.Claims;
using System.Text;

namespace SENSEI.WEB.Controllers
{
    public class SenseiJapaneseSchoolController : Controller
    {
        private readonly ISmsService _smsService;
        private readonly ICourseService _courseService;
        private readonly ILocationService _locationService;
        private readonly IStudentRegistrationService _studentRegistrationService;
        private readonly IUserService _userService;

        public SenseiJapaneseSchoolController
        (
            ISmsService smsService, 
            ICourseService courseService, 
            ILocationService locationService, 
            IStudentRegistrationService studentRegistrationService,
            IUserService userService
        )
        {
            _smsService = smsService;
            _courseService = courseService;
            _locationService = locationService;
            _studentRegistrationService = studentRegistrationService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> Gallery()
        {
            return View();
        }

        public async Task<IActionResult> Practice()
        {
            return View();
        }

        #region Login

        public async Task<IActionResult> Login()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> OTPLogin()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OTPLogin(string phone)
        {
            var otpCode = GlobalHelpers.GenerateOtp();
            var smsStatus = false;
            var phoneNo = "94" + phone.ToString();

            var user = await _userService.GetUserByPhone("+" + phoneNo);

            if (user is null)
            {
                TempData.AddNotification(new NotificationMessage
                {
                    Type = "Error",
                    Message = "Your account is not registered."
                });

                return RedirectToAction("Login");
            }

            var message = $"Your OTP code is {otpCode}. This code is valid for 5 minutes.";

            var userOtp = new User
            {
                UserId = user.UserId,
                LastOtpSequence = Convert.ToInt32(otpCode),
            };

            var optupdated = await _userService.UpdateOtpSequence(userOtp);

            if (optupdated)
            {
                smsStatus = await _smsService.SendSingleAsync(phoneNo, message);
            }

            if (!smsStatus)
            {
                TempData.AddNotification(new NotificationMessage
                {
                    Type = "Error",
                    Message = "OTP sent failed!"
                });

                return RedirectToAction("Login");
            }

            TempData.AddNotification(new NotificationMessage
            {
                Type = "success",
                Message = "OTP sent successfully!"
            });

            return RedirectToAction("OtpConfirm", new { userGlobalIdentity = user.UserGlobalidentity, phone = phone });
        }

        [HttpGet]
        public async Task<IActionResult> OtpConfirm(string userGlobalIdentity, int phone)
        {
            ViewBag.UserGlobalIdentity = userGlobalIdentity;
            ViewBag.Phone = phone;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> OtpConfirm(string userGlobalIdentity, int phone, int otpCode)
        {
            ViewBag.UserGlobalIdentity = userGlobalIdentity;

            var user = await _userService.GetUserByUserGlobalIdentity(userGlobalIdentity);

            if (user is null || user.LastOtpSequence != otpCode)
            {
                TempData.AddNotification(new NotificationMessage
                {
                    Type = "Error",
                    Message = "Invalid OTP code."
                });

                return RedirectToAction("Login");
            }

            HttpContext.Session.SetString("UserId", user.UserId.ToString());
            HttpContext.Session.SetString("UserName", user.userName);
            HttpContext.Session.SetString("DisplayName", user.Staff != null ? user.Staff.StaffPopulatedName : user.Student.StudentPopulatedName);
            HttpContext.Session.SetString("UserType", user.UserTypeEnum.ToString());
            HttpContext.Session.SetString("ProfileImage", "/theme/v1/img/avatars/placeholder_1.jpeg");

            if (user.UserTypeEnum == UserTypeEnum.Admin)
            {
                HttpContext.Session.SetString("EmployeeId", user.Staff.EmployeeId.ToString());
            
            }
            else if (user.UserTypeEnum == UserTypeEnum.Manager)
            {
                HttpContext.Session.SetString("EmployeeId", user.Staff.EmployeeId.ToString());
            }
            else if (user.UserTypeEnum == UserTypeEnum.Student)
            {
                HttpContext.Session.SetString("StudentId", user.Student.StudentId.ToString());
            }
            else
            {

            }


                var appClaims = new List<Claim>
            {
                new Claim("UserId", user.UserId.ToString()),
                new Claim(ClaimTypes.Email, user.userName),
                new Claim(ClaimTypes.Name, user.Staff != null ? user.Staff.StaffPopulatedName : user.Student.StudentPopulatedName),
                new Claim(ClaimTypes.Role, user.UserTypeEnum.ToString())
            };

            var identity = new ClaimsIdentity(appClaims, CookieAuthenticationDefaults.AuthenticationScheme);
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties { IsPersistent = true });

            TempData.AddNotification(new NotificationMessage
            {
                Type = "Success",
                Message = "Login successful!"
            });

            TempData.AddNotification(new NotificationMessage
            {
                Type = "info",
                Message = $"Welcome {user?.Staff?.StaffPopulatedName ?? user?.Student?.StudentPopulatedName ?? "User"}"
            });

            if (user.UserTypeEnum == UserTypeEnum.Admin)
            {
                return RedirectToAction("Index", "Home", new { Area = "Adminportal" });

            }
            else if (user.UserTypeEnum == UserTypeEnum.Manager)
            {
                return RedirectToAction("Index", "Home", new { Area = "Adminportal" });
            }
            else if (user.UserTypeEnum == UserTypeEnum.Student)
            {
                return RedirectToAction("Index", "Home", new { Area = "Studentportal" });
            }
            else
            {
                TempData.AddNotification(new NotificationMessage
                {
                    Type = "error",
                    Message = "Your account did not match any type"
                });
                return RedirectToAction("Login");
            }
            
        }

        #endregion

        #region Registration

        [HttpGet]
        public async Task<IActionResult> Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(StudentRegistration studentRegistration)
        {
            //if (!ModelState.IsValid)
            //{
            //    return View(studentRegistration);
            //}

            var isEmailUnique = await _userService.GetUserByEmail(studentRegistration.Email);
            
            if (isEmailUnique != null)
            {
                TempData.AddNotification(new NotificationMessage
                {
                    Type = "Error",
                    Message = "This email is already registered.!"
                });
                return View(studentRegistration);
            }

            var (status, primaryKey) = await _studentRegistrationService.UpdateStudentRegistraion(studentRegistration);

            if (status)
            {
                var phone = studentRegistration.PhoneNo?.Replace("+", "");

                var message = $"Your registration with sensei japanese center was successfull. You will get notified when an admin approve your registration request.";

                var messageStatus = await _smsService.SendSingleAsync(phone, message);

                TempData.AddNotification(new NotificationMessage
                {
                    Type = "success",
                    Message = "Registration success!"
                });

                return RedirectToAction("Login");
            }

            TempData.AddNotification(new NotificationMessage
            {
                Type = "error",
                Message = "registration Failed!"
            });

            return View();
        }
        #endregion

        #region Google Authentication

        public async Task<IActionResult> SigninGoogle()
        {
            var properties = new AuthenticationProperties
            {
                RedirectUri = Url.Action("GoogleResponse")
            };

            return Challenge(properties, GoogleDefaults.AuthenticationScheme);
        }

        public async Task<IActionResult> GoogleResponse()
        {

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/AdminPortalFooter.cshtml
@{
	Layout = null;
}

<footer class="footer">
	<div class="container-fluid">
		<div class="row align-items-center">
			<div class="col-md-4 text-start">
				<p class="mb-0">
					<span class="fw-bold" style="color: var(--primary); font-family: 'Noto Serif JP', serif;">Sensei Japanese Center</span><br />
					<small class="text-muted text-uppercase fw-bold" style="font-size: 0.65rem; letter-spacing: 0.05em;">&copy; @DateTime.Now.Year All rights reserved.</small>
				</p>
			</div>
			<div class="col-md-4 text-center d-none d-md-block">
				<div class="d-flex justify-content-center gap-4">
					<div class="text-muted small">
						<i class="fas fa-map-marker-alt text-primary me-1"></i> <span class="fw-bold">Matara</span>
					</div>
					<div class="text-muted small">
						<i class="fas fa-map-marker-alt text-primary me-1"></i> <span class="fw-bold">Galle</span>
					</div>
				</div>
			</div>
			<div class="col-md-4 text-end">
				<ul class="list-inline mb-0">
					<li class="list-inline-item">
						<a class="text-muted fw-bold text-decoration-none small" href="~/" target="_blank">Public Site</a>
					</li>
					<li class="list-inline-item ms-3">
						<a class="text-muted fw-bold text-decoration-none small" href="#">Support</a>
					</li>
					<li class="list-inline-item ms-3">
						<a class="text-muted fw-bold text-decoration-none small" href="https://wa.me/94773833011" target="_blank">
							<i class="fab fa-whatsapp text-success me-1"></i> WhatsApp
						</a>
					</li>
					<li class="list-inline-item ms-3">
						<a class="text-muted fw-bold text-decoration-none small" href="#">Privacy</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/AdminPortalHeader.cshtml
@using core_web.Helpers

@{
	Layout = null;
}

<nav class="navbar navbar-expand navbar-light navbar-bg">
	<div class="d-flex align-items-center">
		<a class="sidebar-toggle js-sidebar-toggle ms-2">
			<i class="hamburger align-self-center"></i>
		</a>
		<div class="ms-3 d-flex align-items-center gap-2 gap-md-4">
			<div class="brand-text d-flex align-items-center" style="gap: 8px;">
				<img src="@Url.Content("~/theme/v1/img/photos/name1.png")" alt="Sensei Japanese Center" class="brand-name-img header-logo-res" />
				<img src="@Url.Content("~/theme/v1/img/photos/name.png")" alt="Name" class="brand-name-img header-logo-res d-none d-sm-block" />
			</div>
			<span class="admin-badge d-none d-md-inline-block ms-1">Admin Console</span>
		</div>
	</div>

	<div class="navbar-collapse collapse">
		<ul class="navbar-nav navbar-align">

			<!-- notification -->
			@Html.RenderAction("AdminPortalNotification", "Layout", new { area = "" })

			<!-- message -->
			@* @Html.RenderAction("AdminPortalMessages", "Layout", new { area = "" }) *@


			<!-- profile -->
			@Html.RenderAction("AdminPortalProfile", "Layout", new { area = "" })

		</ul>
	</div>
</nav>

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/AdminPortalMessages.cshtml
@{
	Layout = null;
}

<li class="nav-item dropdown">
	<a class="nav-icon dropdown-toggle" href="#" id="messagesDropdown" data-bs-toggle="dropdown">
		<div class="position-relative">
			<i class="align-middle" data-feather="message-square"></i>
		</div>
	</a>
	<div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="messagesDropdown">
		<div class="dropdown-menu-header">
			<div class="position-relative">
				4 New Messages
			</div>
		</div>
		<div class="list-group">
			<a href="#" class="list-group-item">
				<div class="row g-0 align-items-center">
					<div class="col-2">
						<img src="~/theme/v1/img/avatars/avatar-5.jpg" class="avatar img-fluid rounded-circle" alt="Vanessa Tucker">
					</div>
					<div class="col-10 ps-2">
						<div class="text-dark">Vanessa Tucker</div>
						<div class="text-muted small mt-1">Nam pretium turpis et arcu. Duis arcu tortor.</div>
						<div class="text-muted small mt-1">15m ago</div>
					</div>
				</div>
			</a>
			<a href="#" class="list-group-item">
				<div class="row g-0 align-items-center">
					<div class="col-2">
						<img src="~/theme/v1/img/avatars/avatar-2.jpg" class="avatar img-fluid rounded-circle" alt="William Harris">
					</div>
					<div class="col-10 ps-2">
						<div class="text-dark">William Harris</div>
						<div class="text-muted small mt-1">Curabitur ligula sapien euismod vitae.</div>
						<div class="text-muted small mt-1">2h ago</div>
					</div>
				</div>
			</a>
			<a href="#" class="list-group-item">
				<div class="row g-0 align-items-center">
					<div class="col-2">
						<img src="~/theme/v1/img/avatars/avatar-4.jpg" class="avatar img-fluid rounded-circle" alt="Christina Mason">
					</div>
					<div class="col-10 ps-2">
						<div class="text-dark">Christina Mason</div>
						<div class="text-muted small mt-1">Pellentesque auctor neque nec urna.</div>
						<div class="text-muted small mt-1">4h ago</div>
					</div>
				</div>
			</a>
			<a href="#" class="list-group-item">
				<div class="row g-0 align-items-center">
					<div class="col-2">
						<img src="~/theme/v1/img/avatars/avatar-3.jpg" class="avatar img-fluid rounded-circle" alt="Sharon Lessman">
					</div>
					<div class="col-10 ps-2">
						<div class="text-dark">Sharon Lessman</div>
						<div class="text-muted small mt-1">Aenean tellus metus, bibendum sed, posuere ac, mattis non.</div>
						<div class="text-muted small mt-1">5h ago</div>
					</div>
				</div>
			</a>
		</div>
		<div class="dropdown-menu-footer">
			<a href="#" class="text-muted">Show all messages</a>
		</div>
	</div>
</li>

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/AdminPortalNotification.cshtml
@using SENSEI.DOMAIN
@model IEnumerable<UserNotification>

@{
	Layout = null;
}

<li class="nav-item dropdown">
	<a class="nav-icon dropdown-toggle" href="#" id="alertsDropdown" data-bs-toggle="dropdown">
		<div class="position-relative">
			<i class="align-middle" data-feather="bell"></i>
			<span class="indicator">@Model.Count()</span>
		</div>
	</a>
	<div class="dropdown-menu dropdown-menu-lg dropdown-menu-end py-0" aria-labelledby="alertsDropdown">
		<div class="dropdown-menu-header">

			@if (@Model.Count() > 0)
			{
				@Model.Count() <span>New Notifications</span>
			}
			else
			{
				<span>No Notifications</span>
			}
			
		</div>
		<div class="list-group" id="userNotificationlist">

			@{
				@if (@Model.Count() > 0)
				{
					foreach(var userNotification in Model)
					{
						<a href="#" class="list-group-item">
							<div class="row g-0 align-items-center">
								<div class="col-2">
									<i class="text-warning" data-feather="@userNotification.Icon"></i>
								</div>
								<div class="col-10">
									<div class="text-dark">@userNotification.NotificationType</div>
									<div class="text-muted small mt-1">@userNotification.Message</div>
									<div class="text-muted small mt-1">@userNotification.CreatedAt.ToString("dd/MM/yyyy HH:mm")</div>
								</div>
							</div>
						</a>
					}
				}
			}

			
			@* <a href="#" class="list-group-item">
				<div class="row g-0 align-items-center">
					<div class="col-2">
						<i class="text-warning" data-feather="bell"></i>
					</div>
					<div class="col-10">
						<div class="text-dark">Lorem ipsum</div>
						<div class="text-muted small mt-1">Aliquam ex eros, imperdiet vulputate hendrerit et.</div>
						<div class="text-muted small mt-1">2h ago</div>
					</div>
				</div>
			</a>
			<a href="#" class="list-group-item">
				<div class="row g-0 align-items-center">
					<div class="col-2">
						<i class="text-primary" data-feather="home"></i>
					</div>
					<div class="col-10">
						<div class="text-dark">Login from 192.186.1.8</div>
						<div class="text-muted small mt-1">5h ago</div>
					</div>
				</div>
			</a>
			<a href="#" class="list-group-item">
				<div class="row g-0 align-items-center">
					<div class="col-2">
						<i class="text-success" data-feather="user-plus"></i>
					</div>
					<div class="col-10">
						<div class="text-dark">New connection</div>
						<div class="text-muted small mt-1">Christina accepted your request.</div>
						<div class="text-muted small mt-1">14h ago</div>
					</div>
				</div>
			</a> *@

		</div>

		<div class="dropdown-menu-footer">
			<a href="#" class="text-muted">Click on notification to remove</a>
		</div>

	</div>
</li>

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/AdminPortalProfile.cshtml
@{
	Layout = null;
	var userDisplayName = Context.Session.GetString("DisplayName") ?? "User";
	var userProfileImage = Context.Session.GetString("ProfileImage") ?? "/theme/v1/img/avatars/placeholder_1.jpeg";
}

<li class="nav-item dropdown">
	<a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
		<img src="@Url.Content(userProfileImage)" class="avatar img-fluid rounded-circle" alt="@userDisplayName" style="border: 1px solid var(--primary); width: 28px; height: 28px; object-fit: cover;" onerror="this.src='@Url.Content("/theme/v1/img/avatars/placeholder_1.jpeg")'" />
	</a>

    <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
        <img src="@Url.Content(userProfileImage)" class="avatar img-fluid rounded-circle me-1" alt="@userDisplayName" style="border: 2px solid var(--primary); width: 32px; height: 32px; object-fit: cover;" onerror="this.src='@Url.Content("/theme/v1/img/avatars/placeholder_1.jpeg")'" />
        <span class="text-dark fw-bold">@userDisplayName</span>
    </a>
	<div class="dropdown-menu dropdown-menu-end">
		<a class="dropdown-item" href="pages-profile.html"><i class="align-middle me-1" data-feather="user"></i> Profile</a>
		<div class="dropdown-divider"></div>
		<a asp-area="" asp-controller="SenseiJapaneseSchool" asp-action="LogoutGoogle" class="dropdown-item">Log out</a>
	</div>
</li>

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/AdminSidebar.cshtml
@model List<SENSEI.WEB.Models.SidebarItem>

@{
	Layout = null;
}

<nav id="sidebar" class="sidebar js-sidebar">
	<div class="sidebar-content js-simplebar">
		<a class="sidebar-brand d-flex align-items-center gap-2" href="@Url.Action("Index", "SenseiJapaneseSchool", new { area = "" })">
			<img src="@Url.Content("~/theme/v1/img/photos/logo.PNG")" alt="Logo" style="width: 40px; height: 40px; object-fit: contain;" />
			<div class="d-flex flex-column">
				<span class="align-middle" style="font-weight: 900; color: #ff0000; letter-spacing: -0.04em; font-size: 1.25rem; line-height: 1;">SENSEI</span>
				<span class="align-middle" style="font-weight: 700; color: var(--text-muted); font-size: 0.7rem; text-transform: uppercase; letter-spacing: 0.1em; line-height: 1; margin-top: 4px;">Japanese Center <img src="@Url.Content("~/theme/v1/img/photos/name.png")" alt="Name" style="height: 0.85rem; vertical-align: middle; margin-left: 4px;" /></span>
			</div>
		</a>

		<ul class="sidebar-nav">
			
			@foreach(var item in Model)
			{
				<li class="sidebar-item">
					<a class="sidebar-link" href="@item.Url">
						<i class="align-middle" data-feather="@item.Icon"></i> <span class="align-middle">@item.Title</span>
					</a>
				</li>
			}

		</ul>

		@* <div class="sidebar-cta">
			<div class="sidebar-cta-content">
				<strong class="d-inline-block mb-2">Upgrade to Pro</strong>
				<div class="mb-3 text-sm">
					Are you looking for more components? Check out our premium version.
				</div>
				<div class="d-grid">
					<a href="~/theme/v1/upgrade-to-pro.html" class="btn btn-primary">Upgrade to Pro</a>
				</div>
			</div>
		</div> *@
	</div>
</nav>

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/StudentPortalFooter.cshtml
<footer class="footer">
	<div class="container-fluid">
		<div class="row text-muted">
			<div class="col-6 text-start">
				<p class="mb-0">
					<a class="text-muted" href="#" target="_blank"><strong>SENSEI Japanese School</strong></a> &copy; @DateTime.Now.Year
				</p>
			</div>
			<div class="col-6 text-end">
				<ul class="list-inline">
					<li class="list-inline-item">
						<a class="text-muted" href="#" target="_blank">Support</a>
					</li>
					<li class="list-inline-item">
						<a class="text-muted" href="#" target="_blank">Help Center</a>
					</li>
					<li class="list-inline-item">
						<a class="text-muted" href="#" target="_blank">Privacy</a>
					</li>
					<li class="list-inline-item">
						<a class="text-muted" href="https://wa.me/94773833011" target="_blank"><i class="fab fa-whatsapp text-success me-1"></i> WhatsApp</a>
					</li>
					<li class="list-inline-item">
						<a class="text-muted" href="#" target="_blank">Terms</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</footer>

SENSEI.NETCORE/SENSEI.WEB/Views/Layout/StudentPortalHeader.cshtml
@using core_web.Helpers
@{
	Layout = null;
}

<nav class="navbar navbar-expand navbar-light navbar-bg py-3 px-4 shadow-none" style="z-index:1 !important">
	<div class="d-flex align-items-center">
		<a class="sidebar-toggle js-sidebar-toggle">
			<i class="hamburger align-self-center"></i>
		</a>
		<div class="ms-3 d-none d-md-block">
			<span style="font-weight: 900; color: var(--sensei-red); font-size: 0.9rem; letter-spacing: 0.1em; text-transform: uppercase;">
                Student LMS Portal
            </span>
		</div>
	</div>

	<div class="navbar-collapse collapse">
		<ul class="navbar-nav navbar-align">
			<!-- notification -->
			@Html.RenderAction("AdminPortalNotification", "Layout", new { area = "" })

			<!-- message -->
			@Html.RenderAction("AdminPortalMessages", "Layout", new { area = "" })

			<!-- profile -->
			@Html.RenderAction("AdminPortalProfile", "Layout", new { area = "" })
		</ul>
	</div>
</nav>